---
version: "3"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.177.99.0/24

volumes:
  postgres_data:
  user_data:
  backend_data:

services:
  nginx:
    image: "uxbox-testenv-nginx"
    build:
      context: "."
      dockerfile: "Dockerfile-nginx"

    ports:
      - 8080:80

    networks:
      default:
        ipv4_address: 172.177.99.2

  backend:
    image: "uxbox-testenv-backend"
    build:
      context: "."
      dockerfile: "Dockerfile-backend"

    volumes:
      - backend_data:/opt/data

    depends_on:
      - postgres
      - smtp
      - redis

    environment:
      - APP_DATABASE_URI=postgresql://postgres/uxbox
      - APP_DATABASE_USERNAME=uxbox
      - APP_DATABASE_PASSWORD=uxbox
      - APP_SENDMAIL_BACKEND=smtp
      - APP_SMTP_HOST=smtp
      - APP_SMTP_PORT=25
      - APP_MEDIA_DIRECTORY=/opt/data/media

    networks:
      default:
        ipv4_address: 172.177.99.3


  exporter:
    image: "uxbox-testenv-exporter"
    build:
      context: "."
      dockerfile: "Dockerfile-exporter"

    environment:
      - APP_PUBLIC_URI=http://nginx

    depends_on:
      - backend
      - nginx

    networks:
      default:
        ipv4_address: 172.177.99.4

  smtp:
    image: mwader/postfix-relay:latest
    restart: always
    environment:
      - POSTFIX_myhostname=smtp.testing.uxbox.io
      - OPENDKIM_DOMAINS=smtp.testing.uxbox.io

    networks:
      default:
        ipv4_address: 172.177.99.5

  postgres:
    image: "postgres:12"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=uxbox
      - POSTGRES_USER=uxbox
      - POSTGRES_PASSWORD=uxbox

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      default:
        ipv4_address: 172.177.99.6

  redis:
    image: redis:6
    restart: always

    networks:
      default:
        ipv4_address: 172.177.99.7

